/// The Subleq Spire — Main Entry Point
///
/// An evolutionary battle royale where SUBLEQ programs generated by a
/// constrained Transformer fight to the death in shared memory.
/// Features Self-Play Tournament Pipeline with Hall of Fame,
/// ELO ranking, Curriculum Learning, and Chaos Mode.

mod vm;
mod arena;
mod constraint;
mod transformer;
mod training;
mod elo;

use burn::backend::{Autodiff, NdArray};

type MyBackend = NdArray<f32>;
type MyAutodiffBackend = Autodiff<MyBackend>;

fn main() {
    // Initialize logging
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info"))
        .init();

    log::info!("╔══════════════════════════════════════╗");
    log::info!("║     THE SUBLEQ SPIRE — TOURNAMENT    ║");
    log::info!("║   Self-Play Battle Royale Evolution   ║");
    log::info!("╚══════════════════════════════════════╝");

    // Device setup
    let device = <MyAutodiffBackend as burn::tensor::backend::Backend>::Device::default();

    // Evolution configuration with Tournament Pipeline
    let config = training::EvolutionConfig {
        gladiators_per_battle: 8,       // New gladiators per battle
        num_generations: 100,
        train_steps_per_gen: 5,
        learning_rate: 1e-3,
        temperature: 1.0,
        max_program_tokens: 48,
        buffer_capacity: 1000,
        train_batch_size: 32,
        checkpoint_interval: 10,

        // Hall of Fame
        hof_max_size: 20,               // Top 20 all-time elites
        champions_per_battle: 3,        // 3 gatekeepers per battle
        hof_train_ratio: 0.7,           // 70% HoF, 30% pool in training

        // Curriculum Learning
        curriculum_stages: vec![
            training::CurriculumStage {
                until_generation: 20,
                arena_memory_size: 256,
                gladiator_slot_size: 64,
                max_rounds: 1_000,
            },
            training::CurriculumStage {
                until_generation: 50,
                arena_memory_size: 512,
                gladiator_slot_size: 64,
                max_rounds: 10_000,
            },
            training::CurriculumStage {
                until_generation: usize::MAX,
                arena_memory_size: 1024,
                gladiator_slot_size: 64,
                max_rounds: 50_000,
            },
        ],

        // Chaos Mode
        chaos_stagnation_threshold: 5,  // Chaos after 5 stagnant gens
        chaos_temperature: 2.0,

        transformer_config: transformer::SubleqTransformerConfig::new(),
    };

    log::info!(
        "Config: {} gladiators + {} champions, {} generations",
        config.gladiators_per_battle, config.champions_per_battle, config.num_generations
    );
    log::info!(
        "HoF: max {}, ratio {:.0}% | Chaos: threshold {} gens, temp {:.1}",
        config.hof_max_size, config.hof_train_ratio * 100.0,
        config.chaos_stagnation_threshold, config.chaos_temperature
    );
    log::info!(
        "Curriculum: 256→512→1024 cells over {} gens",
        config.num_generations
    );

    // Run the Tournament Pipeline
    training::evolution_loop::<MyAutodiffBackend>(config, &device);
}
