/// The Subleq Spire — Main Entry Point
///
/// An evolutionary battle royale where SUBLEQ programs generated by a
/// constrained Transformer fight to the death in shared memory.
/// The last survivor's DNA trains the next generation.

mod vm;
mod arena;
mod constraint;
mod transformer;
mod training;

use burn::backend::{Autodiff, NdArray};

type MyBackend = NdArray<f32>;
type MyAutodiffBackend = Autodiff<MyBackend>;

fn main() {
    // Initialize logging
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info"))
        .init();

    log::info!("╔══════════════════════════════════════╗");
    log::info!("║       THE SUBLEQ SPIRE               ║");
    log::info!("║   Battle Royale Code Evolution        ║");
    log::info!("╚══════════════════════════════════════╝");

    // Device setup
    let device = <MyAutodiffBackend as burn::tensor::backend::Backend>::Device::default();

    // Evolution configuration
    let config = training::EvolutionConfig {
        gladiators_per_battle: 10,
        num_generations: 50,
        train_steps_per_gen: 3,
        learning_rate: 1e-3,
        temperature: 1.0,
        max_program_tokens: 48,   // ~16 instructions max
        buffer_capacity: 200,
        arena_config: arena::ArenaConfig {
            memory_size: 1024,
            gladiator_slot_size: 64,
            max_rounds: 50_000,
        },
        transformer_config: transformer::SubleqTransformerConfig::new(),
    };

    log::info!("Config: {} gladiators, {} generations", config.gladiators_per_battle, config.num_generations);
    log::info!("Arena: {} cells, {} per slot", config.arena_config.memory_size, config.arena_config.gladiator_slot_size);

    // Run the evolution loop
    training::evolution_loop::<MyAutodiffBackend>(config, &device);
}
